#!/bin/bash

trap "" SIGTSTP
trap '' SIGINT

HEIGHT=17
CHOICE_HEIGHT=10
WIDTH=78
BACKTITLE="Kali Linux"
TITLE="[ Kali Power Terminal ]"

SMENU="/usr/local/bin/smenu"

main_menu() {
    CHOICE=$(dialog --clear --no-cancel \
        --backtitle "$BACKTITLE" \
        --title "$TITLE" \
        --menu "Main Menu:" \
        $HEIGHT $WIDTH $CHOICE_HEIGHT \
        Recon   "Reconnaissance tools" \
        Exec    "Execution / Exploitation" \
        Wifi    "Wireless attacks" \
        Admin   "Administration" \
        Shell   "Exit to shell" \
        2>&1 > /dev/tty)

    case $CHOICE in
        Recon) recon_menu ;;
        Exec) exec_menu ;;
        Wifi) wifi_menu ;;
        Admin) admin_menu ;;
        Shell) exit ;;
    esac
}

recon_menu() {
    CHOICE=$(dialog --clear \
        --backtitle "$BACKTITLE" \
        --title "[ Reconnaissance ]" \
        --menu "Select Recon Task:" \
        $HEIGHT $WIDTH $CHOICE_HEIGHT \
        nmap    "Nmap scan to detect software versions" \
        dnsenum "DNS Enumeration" \
        wapiti  "Web application vulnerability scanner" \
        discover "Bash scripts to automate various penetration testing tasks" \
        redhawk "Information Gathering And Vulnerability Scanning" \
        sherlock "Hunt down social media accounts by username" \
        netdisco "Discover active hosts (devices) on a local network " \
        nessus   "Vulnerabilities discovery" \
        Harvester "Gather open source intelligence (OSINT) on a company or domain " \
        Back    "Return to main menu" \
        2>&1 > /dev/tty)

    case $CHOICE in
        nmap) /bin/sh ~/Scripts/vulnerabilities.sh ;;
        dnsenum) /bin/sh ~/Scripts/dnsenum.sh ;;
        wapiti) /bin/sh ~/Scripts/wapiti.sh ;;
        discover) /bin/sh ~/Tools/discover/discover.sh ;;
        redhawk) /bin/sh ~/Scripts/rhawk.sh ;;
        sherlock) /bin/sh ~/Scripts/sherlock.sh ;;
        netdisco) /bin/sh ~/Scripts/netdiscover.sh ;;
        nessus) /bin/sh ~/Scripts/nessus.sh ;;
        Harvester) /bin/sh ~/Scripts/harvester.sh ;;
        Back) main_menu ;;
    esac

    recon_menu
}

exec_menu() {
    CHOICE=$(dialog --clear \
        --backtitle "$BACKTITLE" \
        --title "[ Execution ]" \
        --menu "Select Execution Task:" \
        $HEIGHT $WIDTH $CHOICE_HEIGHT \
        metasploit "Launch Metasploit" \
        msfvenom   "MSFvenom payloads" \
        Back       "Return to main menu" \
        2>&1 > /dev/tty)

    case $CHOICE in
        metasploit) msfconsole ;;
        msfvenom) msfvenom ;;
        Back) main_menu ;;
    esac

    exec_menu
}

wifi_menu() {
    CHOICE=$(dialog --clear \
        --backtitle "$BACKTITLE" \
        --title "[ WiFi ]" \
        --menu "Select Wireless Task:" \
        $HEIGHT $WIDTH $CHOICE_HEIGHT \
        monitor_en  "Enable monitor mode" \
        monitor_dis "Disable monitor mode" \
        airodump "Scan WIFI networks and write file" \
        de_auth  "Deauthenticate connected devices" \
        aircrack "Crack WPA handshake" \
        Back    "Return to main menu" \
        2>&1 > /dev/tty)

    case $CHOICE in
        monitor_en) /bin/sh ~/Scripts/monitor_mode.sh ;;
        monitor_dis) /bin/sh ~/Scripts/restart_networkmanager.sh ;;
        airodump) /bin/sh ~/Scripts/airodump_capture.sh ;;
        de_auth) /bin/sh ~/Scripts/kick_devices.sh ;;
        aircrack) /bin/sh ~/Scripts/crack.sh ;;
        Back) main_menu ;;
    esac

    wifi_menu
}

admin_menu() {
    CHOICE=$(dialog --clear \
        --backtitle "$BACKTITLE" \
        --title "[ Administration ]" \
        --menu "System Administration:" \
        $HEIGHT $WIDTH $CHOICE_HEIGHT \
        Start_aut "Start Auto IP Changer" \
        Start_mac_spoof "Spoof MAC Address" \
        Stop_mac_spoof  "Set MAC Address back to vendor" \
        EditMenu "Edit this menu" \
        Lock     "Lock terminal" \
        Logout   "Logout session" \
        Reboot   "Reboot system" \
        Back     "Return to main menu" \
        2>&1 > /dev/tty)

    case $CHOICE in
        Start_aut) sudo aut ;;
        Start_mac_spoof) /bin/sh ~/Scripts/mac_spoofer.sh ;;
        Stop_mac_spoof) /bin/sh ~/Scripts/mac_reset.sh ;;
        EditMenu) sudo vi "$SMENU" ;;
        Lock) /usr/bin/vlock ;;
        Logout) pkill -KILL -u "YOUR_USERNAME" ;;
        Reboot) sudo systemctl reboot ;;
        Back) main_menu ;;
    esac

    admin_menu
}

# Start menu
main_menu
